device: 'cuda:1'
#weights: "/root/skywatch/weights/vigilant/epoch_15.pth"  # path to weights file
weights: "/root/skywatch/weights/oulu/protocol_1/epoch=24.ckpt"  # path to weights file
frames_folder: "/root/skywatch/output/frames/" # path to saved cropped frames for testing

mean:
  r: 0
  g: 0
  b: 0
std:
  r: 1
  g: 1
  b: 1